name: Publish Connector Image
on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo to check out code from. Defaults to the main airbyte repo. Set this when building connectors from forked repos."
        required: false
        default: "airbytehq/airbyte"
      gitref:
        description: "The git ref to check out from the specified repository."
        required: false
        default: master
      connector:
        description: "Airbyte Connector"
        required: true
      comment-id:
        description: "The comment-id of the slash command. Used to update the comment with the status."
        required: false
      auto-bump-version:
        description: "after publishing, the workflow will automatically bump the connector version in definitions and generate seed spec"
        required: true
        default: "true"
      parallel:
        description: "Switching this to true will spin up 5 build agents instead of 1 and allow multi connector publishes to run in parallel"
        required: true
        default: "false"
      run-tests:
        description: "Should run tests when publishing"
        required: true
        default: "true"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.gitref }}
      - name: Mock connection publication
        id: publish
        run: |
          echo "Mock connection publication (sleep for 10 seconds)..."
          sleep 10
          echo "Connector ${{ github.event.inputs.connector }} has been published"
      - name: Mark workflow as completed
        run: |
          export CONNECTOR=${{ github.event.inputs.connector }}
          export CONNECTOR_TYPE=$(echo ${CONNECTOR} | cut -d"-" -f1)
          cat <<-EOF
          {
            "${CONNECTOR_TYPE}s": {
              "${CONNECTOR}": {
                "publish_running": false,
                "publish_run_status": "{{ steps.publish.outcome === 'failure' && '❌' || '✅' }}",
                "publish_run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }
          }
          EOF > connector_report.json
      - name: Run Stoat action
        uses: stoat-dev/stoat-action@liren/airbyte-connector-plugin
        if: always()
